### ISSUE TITLE
Plugin fails with rebar3 version 3.9.1

### ISSUE THREAD

**Issue by fogfish** [benoitc/rebar3_path_deps#1]
The plugin usage workflow uses as-is example from README.md with latest rebar3.

The workflow fails with the following error:

```
===> Failed to fetch and copy dep: {path,"hello_utils",
                                    {mtime,<<"2019-04-21T12:45:40Z">>}}
```

**Comment by fogfish** [comment]
have you had chance to look into this issue? current behaviour is really irritating!

**Comment by benoitc** [comment]
i will have a look during the week-end. I need to upgrade my version of rebar3

**Comment by fogfish** [comment]
Just merge PR #2 and re-publish plugin ;-)

**Comment by fogfish** [comment]
Can you please publish a new version of plugin to hex.pm ?

**Comment by benoitc** [comment]
0.3.0 has been published. Sorry for the delay.
